version: '2'
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - 3000:3000

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongoData:/data/db

  broker:
    build: ./mosca-broker
    container_name: broker
    environment:
      - mongo=mongo
    ports:
      - 1883:1883
      - 1884:1884
    depends_on:
      - mongo

  street-simulator:
    build: ./street-simulator-client
    container_name: street
    depends_on:
      - broker  

  web-client:
    build: ./mqtt-web-client
    container_name: web-client
    ports:
      - 3030:3030
    environment:
      - broker=broker
    depends_on:
      - broker

#  termnial-client:
#    build: ./mqtt-terminal-client
#    container_name: terminal-client
#    environment:
#      - broker=broker
#    depends_on:
#      - broker

volumes:
  mongo_db: